/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booking;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author dell
 */
public class lihat_booking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(lihat_booking.class.getName());
    private DefaultTableModel model;
    /**
     * Creates new form lihat_booking
     */
    public lihat_booking() {
        initComponents();
        
        model = new DefaultTableModel();
        tblBooking.setModel(model);
        model.addColumn("ID");
        model.addColumn("Lapangan");
        model.addColumn("TIM");
        model.addColumn("Mulai & Selesai");
        model.addColumn("Status Bayar");
        
        jButtonDashboard1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new dashboard.dashboard().setVisible(true);
                dispose();
            }
        });
        
        tampilkan_data();
    }
    
    public void tampilkan_data() {
        // Bersihkan data tabel lama sebelum meload yang baru
        model.setRowCount(0);
        
        try {
            Connection conn = koneksi.getConnection();
            
            // Query JOIN agar yang muncul di tabel berupa Nama/Jenis, bukan sekadar ID angka
            String sql = "SELECT b.id_booking, l.jenis_lapangan, p.nama_tim, "
                       + "CONCAT(b.jam_mulai, ' - ', b.jam_selesai) AS waktu, b.status_bayar "
                       + "FROM booking b "
                       + "JOIN lapangan l ON b.id_lapangan = l.id_lapangan "
                       + "JOIN penyewa p ON b.id_penyewa = p.id_penyewa "
                       + "ORDER BY b.id_booking DESC";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                // Ambil data hasil query dan masukkan ke dalam array objek row JTable
                Object[] row = {
                    rs.getString("id_booking"),
                    rs.getString("jenis_lapangan"),
                    rs.getString("nama_tim"),
                    rs.getString("waktu"),
                    rs.getString("status_bayar")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data dashboard: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLaporan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooking = new javax.swing.JTable();
        jButtonDashboard1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard Booking");

        btnLaporan.setText("Print");
        btnLaporan.addActionListener(this::btnLaporanActionPerformed);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        tblBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Lapangan", "Tim", "Mulai&Selesai", "Status Bayar"
            }
        ));
        tblBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBooking);

        jButtonDashboard1.setText("dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButtonDashboard1)
                                .addGap(18, 18, 18)
                                .addComponent(btnLaporan)
                                .addGap(29, 29, 29)
                                .addComponent(btnTambah))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLaporan)
                    .addComponent(btnTambah)
                    .addComponent(jButtonDashboard1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    // Membuka form tambah_booking dengan Constructor kosong (Mode Create Data Baru)
        tambah_booking formTambah = new tambah_booking();
        formTambah.setVisible(true);
        
        // Menutup halaman dashboard ini
        this.dispose();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
    // Validasi: Cek apakah tabel kosong atau tidak sebelum dicetak
        if (tblBooking.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada data transaksi booking untuk dicetak!", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1. Mengatur format judul atas (Header) dan halaman bawah (Footer) pada kertas
            java.text.MessageFormat header = new java.text.MessageFormat("LAPORAN DATA TRANSAKSI BOOKING FUTSAL");
            java.text.MessageFormat footer = new java.text.MessageFormat("Halaman {0,number,integer}");

            // 2. Memanggil fungsi bawaan JTable untuk mencetak komponen dirinya sendiri
            // Mode FIT_WIDTH digunakan agar lebar kolom tabel otomatis muat di kertas (A4/Letter)
            boolean complete = tblBooking.print(javax.swing.JTable.PrintMode.FIT_WIDTH, header, footer);

            // 3. Notifikasi status cetak kepada user/kasir
            if (complete) {
                JOptionPane.showMessageDialog(this, "Laporan berhasil dikirim ke Printer / PDF!", 
                        "Cetak Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Proses cetak laporan dibatalkan oleh pengguna.", 
                        "Cetak Dibatalkan", JOptionPane.WARNING_MESSAGE);
            }

        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Gagal melakukan cetak dokumen: " + e.getMessage(), 
                    "Cetak Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void tblBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookingMouseClicked
    // Ambil baris indeks ke berapa yang sedang diklik oleh user
        int baris = tblBooking.getSelectedRow();
        
        // Ambil semua data dari kolom tabel berdasarkan baris tersebut
        String id_booking = model.getValueAt(baris, 0).toString();
        String lapangan   = model.getValueAt(baris, 1).toString();
        String penyewa    = model.getValueAt(baris, 2).toString();
        
        // Memisahkan teks gabungan waktu "Jam Mulai - Jam Selesai" kembali ke format aslinya
        String waktuFull  = model.getValueAt(baris, 3).toString();
        String mulai      = waktuFull.split(" - ")[0];
        String selesai    = waktuFull.split(" - ")[1];
        
        String status     = model.getValueAt(baris, 4).toString();
        
        // Mengambil data Tanggal langsung dari Database MySQL karena tidak dimunculkan di JTable dashboard
        String tanggal = "";
        try {
            Connection conn = koneksi.getConnection();
            String sql = "SELECT tanggal_main, total_biaya FROM booking WHERE id_booking = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id_booking);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                tanggal = rs.getString("tanggal_main");
                String total = rs.getString("total_biaya");
                
                // Lempar semua data lama ini ke Constructor kedua milik form tambah_booking (Mode EDIT)
                tambah_booking formEdit = new tambah_booking(id_booking, lapangan, penyewa, tanggal, mulai, selesai, total, status);
                formEdit.setVisible(true);
                
                // Tutup dashboard utama
                this.dispose(); 
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil detail data: " + e.getMessage());
        }
    }//GEN-LAST:event_tblBookingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new lihat_booking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButtonDashboard1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblBooking;
    // End of variables declaration//GEN-END:variables
}
