/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lapangan;
import java.awt.Color;
import java.sql.*;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author fauzan
 */
public class lapangan extends javax.swing.JFrame {

    /**
     * Creates new form lapangan
     */
    // Table model for database binding
    private DefaultTableModel tableModel;

    public lapangan() {
        initComponents();
        getContentPane().setBackground(new Color(245, 247, 250));

        // HEADER STYLE
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));

        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jLabel2.setForeground(new java.awt.Color(100, 116, 139));

        // button style
        jButton1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        jButton1.setBackground(new java.awt.Color(22, 163, 74));
        jButton1.setForeground(java.awt.Color.WHITE);

        // Setup table with proper columns
        String[] columns = {"No", "Nama Lapangan", "Deskripsi", "Jenis", "Harga/Jam", "Status"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(tableModel);

        // Button action listener
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        // Load data from database
        loadData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        label2 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        label3 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        label4 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));

        jLabel1.setText("Manajemen Lapangan");

        jLabel2.setText("Kelola data lapangan futsal");

        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Tambah Lapangan");

        label2.setText("Total Lapangan");

        jLabel3.setText("3");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        label3.setText("Tersedia");

        jLabel4.setText("3");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        label4.setText("Maintenance");

        jLabel5.setText("3");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ══════════════════════════════════════════════════════════
    //  DATABASE OPERATIONS
    // ══════════════════════════════════════════════════════════
    private void loadData(String keyword) {
        Connection conn = null;
        PreparedStatement pstTotal = null;
        PreparedStatement pstTersedia = null;
        PreparedStatement pstMaintenance = null;
        PreparedStatement pstData = null;
        ResultSet rsTotal = null;
        ResultSet rsTersedia = null;
        ResultSet rsMaintenance = null;
        ResultSet rsData = null;

        try {
            conn = koneksi.getConnection();
            if (conn == null) {
                JOptionPane.showMessageDialog(this,
                        "Gagal terhubung ke database!\nPastikan MySQL server berjalan.",
                        "Error Koneksi",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ── Count total lapangan ──
            pstTotal = conn.prepareStatement("SELECT COUNT(*) as total FROM lapangan");
            rsTotal = pstTotal.executeQuery();
            if (rsTotal.next()) {
                jLabel3.setText(String.valueOf(rsTotal.getInt("total")));
            }

            // ── Count lapangan tersedia (Aktif) ──
            pstTersedia = conn.prepareStatement("SELECT COUNT(*) as total FROM lapangan WHERE status = 'Aktif'");
            rsTersedia = pstTersedia.executeQuery();
            if (rsTersedia.next()) {
                jLabel4.setText(String.valueOf(rsTersedia.getInt("total")));
            }

            // ── Count maintenance ──
            pstMaintenance = conn.prepareStatement("SELECT COUNT(*) as total FROM lapangan WHERE status = 'Maintenance'");
            rsMaintenance = pstMaintenance.executeQuery();
            if (rsMaintenance.next()) {
                jLabel5.setText(String.valueOf(rsMaintenance.getInt("total")));
            }

            // ── Load table data ──
            tableModel.setRowCount(0);

            String sql;
            if (keyword == null || keyword.trim().isEmpty()) {
                sql = "SELECT nama_lapangan, deskripsi, jenis_lapangan, harga_per_jam, status FROM lapangan ORDER BY nama_lapangan ASC";
                pstData = conn.prepareStatement(sql);
            } else {
                sql = "SELECT nama_lapangan, deskripsi, jenis_lapangan, harga_per_jam, status FROM lapangan "
                        + "WHERE nama_lapangan LIKE ? OR jenis_lapangan LIKE ? OR status LIKE ? "
                        + "ORDER BY nama_lapangan ASC";
                pstData = conn.prepareStatement(sql);
                String searchPattern = "%" + keyword.trim() + "%";
                pstData.setString(1, searchPattern);
                pstData.setString(2, searchPattern);
                pstData.setString(3, searchPattern);
            }

            rsData = pstData.executeQuery();
            NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            int no = 1;

            while (rsData.next()) {
                String nama = rsData.getString("nama_lapangan");
                String deskripsi = rsData.getString("deskripsi");
                String jenis = rsData.getString("jenis_lapangan");
                double harga = rsData.getDouble("harga_per_jam");
                String status = rsData.getString("status");

                String hargaFormatted = formatter.format(harga).replace("Rp", "Rp ") + "/jam";

                tableModel.addRow(new Object[]{no, nama, deskripsi, jenis, hargaFormatted, status});
                no++;
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error saat memuat data: " + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            try { if (rsTotal != null) rsTotal.close(); } catch (SQLException e) { /* ignore */ }
            try { if (rsTersedia != null) rsTersedia.close(); } catch (SQLException e) { /* ignore */ }
            try { if (rsMaintenance != null) rsMaintenance.close(); } catch (SQLException e) { /* ignore */ }
            try { if (rsData != null) rsData.close(); } catch (SQLException e) { /* ignore */ }
            try { if (pstTotal != null) pstTotal.close(); } catch (SQLException e) { /* ignore */ }
            try { if (pstTersedia != null) pstTersedia.close(); } catch (SQLException e) { /* ignore */ }
            try { if (pstMaintenance != null) pstMaintenance.close(); } catch (SQLException e) { /* ignore */ }
            try { if (pstData != null) pstData.close(); } catch (SQLException e) { /* ignore */ }
            try { if (conn != null) conn.close(); } catch (SQLException e) { /* ignore */ }
        }
    }

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {
        // Form fields
        JTextField nameField = new JTextField();
        nameField.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        JTextArea descArea = new JTextArea(3, 20);
        descArea.setLineWrap(true);
        descArea.setWrapStyleWord(true);
        descArea.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        JScrollPane descScroll = new JScrollPane(descArea);

        String[] jenisOptions = {"Futsal", "Badminton", "Basket", "Voli", "Tenis", "Lainnya"};
        JComboBox<String> typeCombo = new JComboBox<>(jenisOptions);
        typeCombo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        JTextField priceField = new JTextField();
        priceField.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        String[] statusOptions = {"Aktif", "Maintenance", "Tidak Aktif"};
        JComboBox<String> statusCombo = new JComboBox<>(statusOptions);
        statusCombo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // Build form panel
        JPanel formPanel = new JPanel();
        formPanel.setLayout(new BoxLayout(formPanel, BoxLayout.Y_AXIS));
        formPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        formPanel.add(new JLabel("Nama Lapangan:"));
        formPanel.add(nameField);
        formPanel.add(Box.createVerticalStrut(8));
        formPanel.add(new JLabel("Deskripsi:"));
        formPanel.add(descScroll);
        formPanel.add(Box.createVerticalStrut(8));
        formPanel.add(new JLabel("Jenis Lapangan:"));
        formPanel.add(typeCombo);
        formPanel.add(Box.createVerticalStrut(8));
        formPanel.add(new JLabel("Harga Per Jam:"));
        formPanel.add(priceField);
        formPanel.add(Box.createVerticalStrut(8));
        formPanel.add(new JLabel("Status:"));
        formPanel.add(statusCombo);

        // Show dialog with OK/Cancel buttons
        int result = JOptionPane.showConfirmDialog(this, formPanel, "Tambah Lapangan Baru",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        // Get values
        String nama = nameField.getText().trim();
        String deskripsi = descArea.getText().trim();
        String jenis = (String) typeCombo.getSelectedItem();
        String hargaText = priceField.getText().trim();
        String status = (String) statusCombo.getSelectedItem();

        // Validation
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama lapangan tidak boleh kosong!", "Validasi Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (hargaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga per jam tidak boleh kosong!", "Validasi Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double harga;
        try {
            harga = Double.parseDouble(hargaText);
            if (harga <= 0) {
                JOptionPane.showMessageDialog(this, "Harga harus lebih dari 0!", "Validasi Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Format harga tidak valid! Masukkan angka.", "Validasi Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Insert to database
        Connection conn = null;
        PreparedStatement pst = null;
        try {
            conn = koneksi.getConnection();
            String sql = "INSERT INTO lapangan (nama_lapangan, deskripsi, jenis_lapangan, harga_per_jam, status) VALUES (?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, deskripsi);
            pst.setString(3, jenis);
            pst.setDouble(4, harga);
            pst.setString(5, status);

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Lapangan berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadData("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan lapangan.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try { if (pst != null) pst.close(); } catch (SQLException e1) { /* ignore */ }
            try { if (conn != null) conn.close(); } catch (SQLException e2) { /* ignore */ }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lapangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
